## What is NumPy?
stands for numerical python, is a  fundamental package for scientific computing in python.It typically hold numeric data. 

While NumPy is optimized for numbers, it can also store non-numeric data like strings, booleans, or dates — as long as the data is still homogeneous.

If we need to store heterogeneous data (e.g., a mix of numbers, strings, lists), you must explicitly set the array's dtype to object. This allows elements to be of different Python types, but comes at the cost of performance and loss of vectorization.

1.provides high performance multidimensional array object and tools for working with these array.

2.It is a linear algebra library for data science with python.

3.Bindings to C libraries, making operations significantly faster than native Python lists.(loopings are handled internally in C in numpy)

4.array structure comes in two forms:

vectors(1-d array) and matrices(2-d array) (and also support higher dimensions)


5.Vectroized operation (element wise operation)

6.contiguous memory allocation

To calculate address for a 1D Numpy array:

address = base_address + index * itemsize

## Why use NumPy?
performance: numpy operations are implemented in c provides a performnace boost compared to traditional python list 

functionality: support a wide range of mathematical algebraic and transformation functions essential for data analysis.
Provides a wide range of mathematical, statistical, and linear algebra functions.
Supports broadcasting, slicing, reshaping, and element-wise operations.
Foundation for many other libraries like pandas, scikit-learn, tensorflow, etc.

## The Array Object

#### Data types and Arrays
NumPy arrays are grid like structure of the same type that are indexed by a tuple of nonnegative integers . The number of dimensions is the rank of the array .The shape of array is tuple of integers giving the size of the array along each dimension

## Why NumPy is Faster?

### Data Structure:
NumPy arrays are homogenous and consist of fixed type(typically numerical data)wchich allows for more efficient storage in memory .In contrast python lists are 
heterogenous which mean they can contain element of different types and each element is stored as a seperate object in memory.

### Memory Layout:
NumPy uses contiguous memory which can be efficiently cached and has benefits from vectorized operations.Python list however are arrays of pointers to objects ,even
when all of them are of the same type

### Built in Operations:
NumPy operations are implemented in C which mean they are compiled and highly optimized for performance.Python's sum() function,while versatile(can handle different types), is implemented in python and iterates in bytecode  which is inherently slower than operations in compiled C used by NumPy.

In [1]:
my_list=[1,2,3]


In [2]:
type(my_list)

list

In [3]:
import numpy as np

__Casting normal python list into array__

In [4]:
np.array(my_list) 

array([1, 2, 3])

In [5]:
arr=np.array(my_list) 
arr

array([1, 2, 3])

__Casting list of list into NumPy array__

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a=np.array([1,2,3,5])

In [9]:
type(a)

numpy.ndarray

In [10]:
print(f'dimension:{a.ndim}')

dimension:1


In [11]:
print("Number of dimension",a.ndim)

Number of dimension 1


In [12]:
print("shape",a.shape)

shape (4,)


In [13]:
print(a[0],a[1])

1 2


In [14]:
a.dtype # returns actual data type thats in array

dtype('int32')

###  Arrays Creation
### Creating arrays using different methods

#### Creating array with range of numbers

np.arange(start,stop,stepsize).It is similar to python built in function range

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2) # if we want even number step size 2

array([0, 2, 4, 6, 8])

In [17]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [18]:
large_list=list(range(10000))
large_array=np.array(range(10000))

In [20]:
%timeit np.sum(large_array)

20.7 µs ± 723 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


10,000 loops each	->Run your code 10,000 times in one measurement batch

7 runs ->	Repeat the batch 7 times

Average time per execution = 114 microseconds

But in different runs, it was sometimes:

slightly faster (114 – 1.69 = ~112.3 µs)

slightly slower (114 + 1.69 = ~115.7 µs)

The np.linspace function from the NumPy library generates linearly spaced numbers between a specified start and end point

np.linspace(starting point,end point,number of elements to be generated or no. of points we want)

In [21]:
np.linspace(1,10,15) # 15 numbers evenly spaced in between 1 and 10

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [22]:
lin_arr=np.linspace(1,9,5)  # 5 numbers evenly space in between 1 and 9
lin_arr

array([1., 3., 5., 7., 9.])

In [23]:
lin_arr[1]-lin_arr[0]

2.0

__Generating arrays filled with ones__

np.ones()

In [24]:
import numpy as np

In [25]:
x=np.ones((3,4)) # dimension 3,4
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
print("Number of dimensions",x.ndim)

Number of dimensions 2


__Generating arrays of all 0's__

we can use np.zeros()

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
# first number in tuple represent number of rows
# second number represent number of columns
y=np.zeros((4,5)) 
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Vectorized Operations:
vectorization in NumPy means performing operations element-wise without using explicit Python loops.
Compare the use of a Python loop vs. vectorized operations for multiplying elements by2

In [29]:
t=[1,2,3]
t*2

[1, 2, 3, 1, 2, 3]

In [30]:
temp=[]
for num in t:
    temp.append(num*2)
temp    

[2, 4, 6]

In [31]:
z=np.array([1,2,3])
z*2

array([2, 4, 6])

In [32]:
a=np.array(range(1,13))
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
%timeit [i*2 for i in a]
# underhood there is for loop which ranges 100000 times under that 
#we have our code .so 100000 times the code run and average of the result is calculated to get the accurate result
%timeit a*2

6.27 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.33 µs ± 81.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Reshaping

In [48]:
a=np.array(range(1,13))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
# reshape 1D array to 2D array
b=a.reshape(3,4) 
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
c=a.reshape(2,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Reshape with -1 to automatically calculate size of one dimension

In [62]:
d=a.reshape(-1,3) # -1 automatically calculate row 
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.random.seed(32)
ranarr=np.random.randint(1,20,8) # give me 8 numbers from 1 to 19
ranarr

array([12,  6,  8,  4,  6, 11, 10,  5])

## Basic Functions:

__np.sum()__

In [51]:
y=np.array([[1,2],[3,4]])
print(y)

[[1 2]
 [3 4]]


In [52]:
print(np.sum(y))

10


In [53]:
print(np.sum(y,axis=0)) # sum of each column

[4 6]


axis 0 is row axis.. so we add all rows together column by column (1 row is getting added to another row)

In [82]:
np.sum(y,axis=1) # sum of each row

array([3, 7])

axis 1 is the column axis. so 1 column is added to another column 

__np.max(),np.min()__

In [66]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [67]:
arr.max()

4

In [68]:
arr.min()

1

In [69]:
arr.argmax() # returns index value

3

In [71]:
arr.argmin()

0

__np.mean()__

In [85]:
arr=np.arange(1,5)
arr=np.reshape(arr,(2,2))

In [86]:
print(arr)

[[1 2]
 [3 4]]


In [87]:
arr.mean()

2.5

In [88]:
np.mean(arr)

2.5

In [91]:
np.mean(arr,axis=0)

array([2., 3.])

In [92]:
print(np.mean(arr,axis=1)) # mean of each row

[1.5 3.5]


__If we dont want to type np.random then we can simply import__

In [36]:
from numpy.random import randint,randn

In [37]:
randint(2,10)

5

In [39]:
randn(1,4)

# 1 row and 4 column

array([[ 1.806225  , -2.0447287 ,  0.72327943,  1.64808753]])

randn means random normal where each value is a random sample from the standard normal distribution centered at 0.

most values will fall between -3 and +3, but there is no hard boundary.