In [2]:
import numpy as np

In [3]:
a=np.arange(1,13) # 12 values

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## reshape function

__numpy.reshape(a, newshape, order='C')__<br>
 a        =Array to be reshaped.<br>
 newshape =int or tuple of ints<br>
 order    ={‘C’, ‘F’, ‘A’}, optional
 
C-order ('C'):Elements are stored row by row. The last index (columns) changes fastest..<br>
Fortran-order ('F'): Elements are stored column by column. The first index (rows) changes fastest.Here,Fill column first<br>
Automatic ('A'): Preserves the input array's memory order.



* This function is very useful when we need to change the dimensions of our data for various calculations or visualizations.
* The number of elements in the original array must match the total number of elements in the reshaped array

In [5]:
np.reshape(a,(6,2),"F")

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [6]:
np.reshape(a,(6,2),"C")

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.reshape(a,(6,2),"A")

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [8]:
 # 2*2*3=12(actual number of elements in a) .
#Represents a 3D array with 2 blocks, 3 rows per block, and 2 columns per row.
c=a.reshape(2,3,2) 
print(c)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
b=np.arange(1,49)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [10]:
b.reshape(2,2,3,4)
# 2 big block ,2 sub block inside big block ,3 rows ,4 column

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]]])

Block 1:

  Sub-block 1: 3×4  
  Sub-block 2: 3×4  

Block 2:

  Sub-block 1: 3×4  
  Sub-block 2: 3×4  


In [11]:
b=b.reshape(2,3,2,2,2) # reshapes into 2x3x2x2x2 matrix

In [12]:
b

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]],


        [[[17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24]]]],



       [[[[25, 26],
          [27, 28]],

         [[29, 30],
          [31, 32]]],


        [[[33, 34],
          [35, 36]],

         [[37, 38],
          [39, 40]]],


        [[[41, 42],
          [43, 44]],

         [[45, 46],
          [47, 48]]]]])

full function

__np.full(shape,fill_value)__<br>
shape=must be in tuple,
fill_value

In [13]:
np.full((4,4),12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [14]:
np.full((3,2),2)

array([[2, 2],
       [2, 2],
       [2, 2]])

### Creating identity matrix using eye() function

__np.eye(N,M=None,K=0)__


Parameters:
    
    1. N=Number of rows.
    
    2. M=Number of columns. If None defaults to N.

    3. K=index of diagonal:0(default) refers to main diagonal,a positive value refers to upper diagonal......(simply shift diagonal position)



Return 2-D array with ones on the diagonal and zeros elsewhere

Rows and columns are equal for identity matrix so we give only 1 digit

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## random() function

1. __np.random.rand(no. of rows,no.of columns)__<br>
     generate value from 0 to 1

In [5]:
np.random.rand(5) # single digit gives 1-D array

array([0.63523551, 0.3343739 , 0.44956912, 0.95808527, 0.56902446])

In [22]:
np.random.rand(3,4) # gives 2-D 

array([[0.36815571, 0.20707895, 0.33233412, 0.69100151],
       [0.28612472, 0.6320001 , 0.9346892 , 0.18296706],
       [0.66033856, 0.43453181, 0.73807064, 0.88507976]])

2. __np.random.randn(no.of random numbers)__


The np.random.randn function generates numbers from a standard normal distribution, which is a bell-shaped curve symmetric around zero. In this distribution:

The mean (average) value is 0.
The standard deviation is 1.

The values can range from negative to positive, with about 68% of the values falling within one standard deviation of the mean (i.e., between -1 and 1), about 95% within two standard deviations (between -2 and 2), and so on.



In [7]:
np.random.randn(2) # gets two random numbers

array([ 0.81881625, -0.76042049])

In [10]:
np.random.randn(4,4) # 2 dimensional

array([[ 0.91651035,  1.27515079,  1.0330999 , -0.33340616],
       [ 0.41795884,  0.25196208, -1.42680367,  1.35144915],
       [ 0.91501317,  0.06649912,  1.83591341, -1.13142893],
       [ 1.07894669, -0.58273582,  0.98344531,  1.4885193 ]])

3.__randint(low,high=None,size=None)__<br>
    low is inclusive and high is exclusive


In [23]:
np.random.randint(0,5) # 0 to 5 random values

0

In [24]:
np.random.randint(1,10,(2,2)) # 2d 3d we need tuple but for 1 d simply give number 

array([[7, 6],
       [9, 3]])

In [27]:
np.random.randint(1,10,2) # For 1D simply give number 

array([4, 8])

max() and argmax()

In [36]:
nparray=np.random.randint(10,90,24)
nparray

array([77, 12, 59, 88, 50, 31, 65, 32, 33, 88, 67, 25, 22, 75, 75, 79, 78,
       35, 51, 89, 52, 18, 56, 14])

In [37]:
np.max(nparray)

89

In [38]:
np.argmax(nparray)

19

In [32]:
np.random.seed(34)
myArray=np.random.randint(10,90,24)
print(myArray)

[43 78 45 79 21 88 39 28 39 39 30 72 15 30 61 29 31 73 82 52 82 87 46 12]


In [56]:
np.max(myArray)

88

In [57]:
np.argmax(myArray)

5

In [58]:
np.min(myArray)

12

In [59]:
np.argmin(myArray)

23

## `concatenate()` function 

`concatenate((a1, a2, ...), axis=0)`

- Join a sequence of arrays along an existing axis.

- a1, a2, ... : sequence of array_like
  - The arrays must have the same shape, except in the dimension corresponding to `axis` (the first, by default).
- axis : int, optional
  - The axis along which the arrays will be joined.
  - If axis is None, arrays are flattened before use.  Default is 0.
  

axis = 0 → join vertically -> diff columns are allowed

(put one array below another)

axis = 1 → join horizontally -> diff rows are allowed

(put one array beside another)

In [62]:
arr1=np.arange(2,20).reshape(6,3)

In [63]:
arr2=np.arange(1,13).reshape(6,2)

In [66]:
np.concatenate([arr1,arr2],axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [65]:
np.concatenate([arr1,arr2],axis=1)

array([[ 2,  3,  4,  1,  2],
       [ 5,  6,  7,  3,  4],
       [ 8,  9, 10,  5,  6],
       [11, 12, 13,  7,  8],
       [14, 15, 16,  9, 10],
       [17, 18, 19, 11, 12]])

In [72]:
arr1.flatten()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [73]:
arr1=np.arange(2,20).reshape(6,3)
arr2=np.arange(4,22).reshape(6,3)

In [ ]:
np.conca

In [87]:
np.random.seed(32)
arr1=np.random.randint(4,20,(2,3,2))
arr1

array([[[11, 15],
        [ 9, 10],
        [16, 18]],

       [[12,  7],
        [16, 11],
        [18, 13]]])

In [88]:
arr1[0]

array([[11, 15],
       [ 9, 10],
       [16, 18]])

In [89]:
arr1[1][0][0]

12

In [90]:
np.indices((2,3,2)) # position for accessing

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[0, 0],
         [1, 1],
         [2, 2]],

        [[0, 0],
         [1, 1],
         [2, 2]]],


       [[[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]]]])